import { PlanetName, LineType } from "./types";

interface Interpretation {
  title: string;
  shortDesc: string;
  livingHere: string;
  themes: string[];
  bestFor: string[];
  challenges: string[];
}

const interpretations: Record<string, Interpretation> = {
  "sun-MC": {
    title: "Sun on the Midheaven",
    shortDesc: "This is your power line. Places along this line amplify your visibility, career success, and public recognition.",
    livingHere: "Living here puts you in the spotlight. You'll feel drawn to leadership roles and may find that opportunities for career advancement come more easily. People see you clearly here - your identity shines through in everything you do.",
    themes: ["Career success", "Public recognition", "Leadership", "Identity"],
    bestFor: ["Starting a business", "Building a public career", "Finding your purpose", "Gaining authority"],
    challenges: ["Pressure to perform", "Constant visibility can be exhausting", "Ego inflation"],
  },
  "sun-IC": {
    title: "Sun at the Nadir",
    shortDesc: "A deeply personal line where you connect with your roots, family, and innermost self.",
    livingHere: "This location illuminates your private life and inner world. You may feel drawn to understanding your family history, creating a beautiful home, or doing deep inner work. It's a place of quiet self-discovery.",
    themes: ["Home life", "Family roots", "Inner self", "Foundations"],
    bestFor: ["Settling down", "Healing family wounds", "Finding your roots", "Inner growth"],
    challenges: ["May feel too private or isolated", "Family drama surfacing", "Difficulty with public life"],
  },
  "sun-ASC": {
    title: "Sun on the Ascendant",
    shortDesc: "Your vitality line. Here you radiate confidence, health, and personal magnetism.",
    livingHere: "You'll feel more alive and energetic here than almost anywhere else. Your personality becomes magnetic, and people are naturally drawn to you. Physical health tends to improve, and you feel aligned with your true self.",
    themes: ["Vitality", "Self-expression", "Confidence", "Physical health"],
    bestFor: ["Personal reinvention", "Health recovery", "Building confidence", "New beginnings"],
    challenges: ["Can become self-centered", "Burnout from constant output", "Others may find you intense"],
  },
  "sun-DSC": {
    title: "Sun on the Descendant",
    shortDesc: "Your partnership line. Relationships with powerful, significant others flourish here.",
    livingHere: "Partnerships define your experience in this location. You may meet important people, find a significant other, or form powerful business partnerships. Others reflect your best qualities back to you.",
    themes: ["Partnerships", "Marriage", "Key relationships", "Collaboration"],
    bestFor: ["Finding love", "Business partnerships", "Diplomacy", "Legal matters"],
    challenges: ["Over-reliance on others", "Losing yourself in relationships", "Power struggles with partners"],
  },
  "moon-MC": {
    title: "Moon on the Midheaven",
    shortDesc: "Your emotional reputation line. You're known for your nurturing, intuitive qualities here.",
    livingHere: "Your emotional nature becomes visible to the public. You may be drawn to caregiving professions, working with women, or fields involving food, home, or family. Your intuition guides your career choices.",
    themes: ["Emotional visibility", "Nurturing career", "Public intuition", "Popularity"],
    bestFor: ["Caregiving professions", "Real estate", "Food industry", "Working with the public"],
    challenges: ["Emotional vulnerability in public", "Mood swings affecting career", "Feeling exposed"],
  },
  "moon-IC": {
    title: "Moon at the Nadir",
    shortDesc: "Your emotional home. This is where you feel the deepest sense of belonging and emotional security.",
    livingHere: "This may be the most emotionally comfortable place on earth for you. You feel at home, connected to the land, and emotionally nourished. Strong connections to family and ancestry emerge here.",
    themes: ["Emotional security", "Home", "Ancestry", "Belonging"],
    bestFor: ["Raising a family", "Emotional healing", "Connecting with heritage", "Finding peace"],
    challenges: ["Can become overly domestic", "Difficulty leaving", "Emotional dependency on place"],
  },
  "moon-ASC": {
    title: "Moon on the Ascendant",
    shortDesc: "Your emotional expression line. Feelings flow freely and your intuition is heightened.",
    livingHere: "You become more emotionally open and intuitive here. Others see your sensitivity as a strength. You may develop psychic abilities or a deeper connection to your emotional body. Creativity flows naturally.",
    themes: ["Emotional expression", "Intuition", "Sensitivity", "Creativity"],
    bestFor: ["Creative pursuits", "Healing work", "Emotional growth", "Connecting with others"],
    challenges: ["Emotional overwhelm", "Hypersensitivity", "Boundary issues"],
  },
  "moon-DSC": {
    title: "Moon on the Descendant",
    shortDesc: "Your emotional partnership line. Deep, nurturing relationships form here.",
    livingHere: "Relationships in this location have a deeply emotional, nurturing quality. You attract caring partners and form bonds that feel like family. Emotional intimacy comes easily.",
    themes: ["Emotional bonds", "Nurturing partners", "Intimacy", "Domestic partnerships"],
    bestFor: ["Finding emotional support", "Marriage", "Building family", "Therapeutic relationships"],
    challenges: ["Codependency", "Attracting emotionally needy partners", "Smothering tendencies"],
  },
  "mercury-MC": {
    title: "Mercury on the Midheaven",
    shortDesc: "Your intellectual reputation line. You're known for your mind, communication, and ideas here.",
    livingHere: "Your mental abilities are recognized and valued. You may excel in writing, teaching, media, technology, or commerce. Ideas flow freely and you find the right words to express them.",
    themes: ["Communication", "Intellectual recognition", "Writing", "Teaching"],
    bestFor: ["Writing career", "Teaching", "Media work", "Technology", "Commerce"],
    challenges: ["Overthinking", "Scattered energy", "Nervous tension"],
  },
  "mercury-IC": {
    title: "Mercury at the Nadir",
    shortDesc: "Your intellectual roots. A place of deep thinking, study, and mental exploration.",
    livingHere: "This location stimulates your inner mind. You may feel drawn to study, research, or deep contemplation. Communication with family improves, and you develop a more analytical understanding of your roots.",
    themes: ["Study", "Research", "Inner dialogue", "Family communication"],
    bestFor: ["Academic pursuits", "Writing a book", "Learning new skills", "Family therapy"],
    challenges: ["Mental restlessness", "Overthinking personal matters", "Information overload"],
  },
  "mercury-ASC": {
    title: "Mercury on the Ascendant",
    shortDesc: "Your communication power line. You become articulate, witty, and mentally sharp here.",
    livingHere: "Your communication skills reach their peak. You become more articulate, quick-witted, and intellectually curious. This is an excellent place for any work involving language, ideas, or technology.",
    themes: ["Articulation", "Mental agility", "Curiosity", "Networking"],
    bestFor: ["Public speaking", "Networking", "Learning languages", "Starting studies"],
    challenges: ["Anxiety", "Restlessness", "Difficulty with emotional depth"],
  },
  "mercury-DSC": {
    title: "Mercury on the Descendant",
    shortDesc: "Your intellectual partnership line. You attract mentally stimulating partners here.",
    livingHere: "Relationships here are built on intellectual connection. You attract partners who stimulate your mind, and communication in partnerships flows easily. Business negotiations tend to go well.",
    themes: ["Intellectual partnerships", "Communication in relationships", "Business deals"],
    bestFor: ["Finding intellectual partners", "Business negotiations", "Contracts", "Collaboration"],
    challenges: ["Relationships may lack emotional depth", "Too much talking, not enough feeling"],
  },
  "venus-MC": {
    title: "Venus on the Midheaven",
    shortDesc: "Your beauty and harmony line. You're known for your charm, artistry, and good taste here.",
    livingHere: "Beauty and harmony define your public image. You may be drawn to the arts, fashion, design, or diplomacy. People find you attractive and charming, and success comes through grace rather than force.",
    themes: ["Beauty", "Art", "Charm", "Social grace", "Luxury"],
    bestFor: ["Art career", "Fashion", "Interior design", "Social climbing", "Diplomacy"],
    challenges: ["Vanity", "Superficiality", "Overspending on luxury"],
  },
  "venus-IC": {
    title: "Venus at the Nadir",
    shortDesc: "Your beautiful home line. Where you create the most beautiful, harmonious living space.",
    livingHere: "Your home becomes a sanctuary of beauty and comfort. You may invest heavily in creating a gorgeous living space. Family relationships become more harmonious and loving.",
    themes: ["Beautiful home", "Family harmony", "Comfort", "Inner peace"],
    bestFor: ["Creating a dream home", "Family healing", "Artistic retreat", "Finding inner beauty"],
    challenges: ["Overindulgence", "Avoiding conflict at home", "Material attachment"],
  },
  "venus-ASC": {
    title: "Venus on the Ascendant",
    shortDesc: "Your love and beauty line. You become irresistibly attractive and socially magnetic here.",
    livingHere: "This is perhaps the most pleasant line to live on. You feel more attractive, both physically and socially. Romance comes easily, as does financial luck. Life feels lighter and more enjoyable.",
    themes: ["Attraction", "Romance", "Social ease", "Financial luck"],
    bestFor: ["Finding love", "Social life", "Financial improvement", "Self-care"],
    challenges: ["Laziness", "Over-indulgence", "Superficial connections"],
  },
  "venus-DSC": {
    title: "Venus on the Descendant",
    shortDesc: "Your ideal love line. Where you're most likely to find your soulmate.",
    livingHere: "This is one of the most powerful lines for love and partnership. Romantic relationships formed here tend to be beautiful, harmonious, and deeply satisfying. You attract loving, artistic partners.",
    themes: ["Soulmate connections", "Romantic love", "Beautiful partnerships", "Harmony"],
    bestFor: ["Finding a life partner", "Marriage", "Artistic collaboration", "Social partnerships"],
    challenges: ["Idealization of partners", "Avoiding necessary conflicts", "Codependency"],
  },
  "mars-MC": {
    title: "Mars on the Midheaven",
    shortDesc: "Your ambition and drive line. Aggressive career moves and bold actions are amplified here.",
    livingHere: "Your competitive drive reaches its peak. You become more assertive, ambitious, and willing to fight for what you want. Career advances come through bold action and courage.",
    themes: ["Ambition", "Competition", "Courage", "Physical energy"],
    bestFor: ["Athletic careers", "Military service", "Entrepreneurship", "Competitive fields"],
    challenges: ["Conflicts with authority", "Burnout", "Aggressive reputation"],
  },
  "mars-IC": {
    title: "Mars at the Nadir",
    shortDesc: "Your inner fire line. Deep emotional energy and passion emerge from within.",
    livingHere: "Your inner fire burns hot here. You may renovate your home, deal with family conflicts head-on, or discover a deep well of personal power. Energy is directed inward.",
    themes: ["Inner strength", "Home renovation", "Family conflicts", "Personal power"],
    bestFor: ["Home improvement", "Resolving family issues", "Building inner strength"],
    challenges: ["Domestic conflicts", "Anger at family", "Restlessness at home"],
  },
  "mars-ASC": {
    title: "Mars on the Ascendant",
    shortDesc: "Your warrior line. Physical energy, courage, and assertiveness are supercharged here.",
    livingHere: "You become physically stronger, more courageous, and more assertive. This is the line of the warrior - you feel ready to take on any challenge. Sports and physical activities bring great satisfaction.",
    themes: ["Physical power", "Courage", "Assertiveness", "Action"],
    bestFor: ["Athletic training", "Physical challenges", "Starting new ventures", "Self-defense"],
    challenges: ["Accidents", "Impulsiveness", "Confrontations", "Physical strain"],
  },
  "mars-DSC": {
    title: "Mars on the Descendant",
    shortDesc: "Your passionate partnership line. Relationships are intense, passionate, and sometimes combative.",
    livingHere: "Partnerships here are passionate and intense. You attract strong-willed partners who challenge you. Sexual chemistry is high, but so is the potential for conflict. Relationships push you to grow.",
    themes: ["Passionate partnerships", "Sexual chemistry", "Conflict", "Growth through others"],
    bestFor: ["Passionate romance", "Business competitors", "Martial arts partnerships"],
    challenges: ["Arguments with partners", "Attracting aggressive people", "Power struggles"],
  },
  "jupiter-MC": {
    title: "Jupiter on the Midheaven",
    shortDesc: "Your success and expansion line. Career opportunities and abundance flow to you here.",
    livingHere: "This is one of the best lines for career success and public recognition. Opportunities seem to fall into your lap. Your reputation grows, and people see you as wise, generous, and successful.",
    themes: ["Career expansion", "Abundance", "Wisdom", "Good fortune"],
    bestFor: ["Career advancement", "Higher education", "Legal matters", "Publishing", "Travel industry"],
    challenges: ["Overconfidence", "Overexpansion", "Taking too many risks"],
  },
  "jupiter-IC": {
    title: "Jupiter at the Nadir",
    shortDesc: "Your abundant home line. Domestic life expands with generosity, space, and optimism.",
    livingHere: "Your home life becomes expansive and abundant. You may live in a larger house, have a generous family life, or feel deeply optimistic about your roots. This is an excellent line for owning property.",
    themes: ["Abundant home", "Family growth", "Property", "Inner optimism"],
    bestFor: ["Buying property", "Expanding family", "Retirement", "Inner spiritual growth"],
    challenges: ["Overspending on home", "Family overindulgence", "Restlessness"],
  },
  "jupiter-ASC": {
    title: "Jupiter on the Ascendant",
    shortDesc: "Your luck and expansion line. Everything feels possible and opportunities abound.",
    livingHere: "You feel luckier, more optimistic, and more expansive here than anywhere else. People see you as generous and wise. Travel opportunities increase, and you may gain weight (Jupiter expands everything!).",
    themes: ["Luck", "Optimism", "Expansion", "Generosity"],
    bestFor: ["New beginnings", "Travel", "Education", "Spiritual growth", "Legal matters"],
    challenges: ["Weight gain", "Over-optimism", "Excess in all things"],
  },
  "jupiter-DSC": {
    title: "Jupiter on the Descendant",
    shortDesc: "Your beneficial partnership line. You attract generous, wise, and fortunate partners.",
    livingHere: "Partnerships here bring growth and abundance. You attract generous, successful partners who expand your worldview. Marriage and business partnerships tend to bring good fortune.",
    themes: ["Fortunate partnerships", "Wise partners", "Growth through others"],
    bestFor: ["Finding a wealthy partner", "Business partnerships", "Legal partnerships", "International relationships"],
    challenges: ["Partners may be excessive", "Codependency through comfort", "Legal overreach"],
  },
  "saturn-MC": {
    title: "Saturn on the Midheaven",
    shortDesc: "Your discipline and structure line. Hard work, responsibility, and lasting achievement define you here.",
    livingHere: "Success here comes through patience, discipline, and hard work. You may face career challenges, but the achievements you build are lasting. Authority figures play an important role.",
    themes: ["Discipline", "Authority", "Lasting achievement", "Responsibility"],
    bestFor: ["Building a legacy", "Government work", "Management", "Long-term goals"],
    challenges: ["Career delays", "Heavy responsibilities", "Feeling burdened", "Depression"],
  },
  "saturn-IC": {
    title: "Saturn at the Nadir",
    shortDesc: "Your foundation line. Deep work on personal foundations, family karma, and inner structure.",
    livingHere: "This location brings you face-to-face with family patterns and personal foundations. You may feel isolated or burdened by domestic responsibilities, but the inner work you do here is profound and lasting.",
    themes: ["Family karma", "Inner structure", "Foundations", "Solitude"],
    bestFor: ["Deep inner work", "Therapy", "Building foundations", "Dealing with the past"],
    challenges: ["Loneliness", "Family burdens", "Feeling restricted", "Depression"],
  },
  "saturn-ASC": {
    title: "Saturn on the Ascendant",
    shortDesc: "Your maturity line. You become more serious, disciplined, and respected here.",
    livingHere: "Life takes on a more serious tone. You become more disciplined, mature, and responsible. Others see you as an authority figure. Physical vitality may decrease, but wisdom increases.",
    themes: ["Maturity", "Discipline", "Authority", "Seriousness"],
    bestFor: ["Self-discipline", "Career building", "Earning respect", "Aging gracefully"],
    challenges: ["Depression", "Loneliness", "Physical limitations", "Pessimism"],
  },
  "saturn-DSC": {
    title: "Saturn on the Descendant",
    shortDesc: "Your committed partnership line. Serious, lasting relationships with mature partners.",
    livingHere: "Relationships here are serious and committed. You attract older or more mature partners. Partnerships may feel restrictive but teach valuable lessons about commitment and responsibility.",
    themes: ["Committed relationships", "Mature partners", "Lessons in love", "Loyalty"],
    bestFor: ["Finding a stable partner", "Marriage", "Business partnerships", "Learning commitment"],
    challenges: ["Feeling trapped", "Cold or distant partners", "Relationship delays"],
  },
  "uranus-MC": {
    title: "Uranus on the Midheaven",
    shortDesc: "Your revolution line. Sudden career changes, innovation, and unconventional success.",
    livingHere: "Your career takes unexpected turns. You may be drawn to technology, innovation, or revolutionary causes. Success comes through being different and embracing change.",
    themes: ["Innovation", "Sudden changes", "Technology", "Rebellion"],
    bestFor: ["Tech careers", "Innovation", "Social activism", "Breaking conventions"],
    challenges: ["Career instability", "Sudden reversals", "Difficulty with authority"],
  },
  "uranus-IC": {
    title: "Uranus at the Nadir",
    shortDesc: "Your awakening line. Deep inner changes and unconventional home life.",
    livingHere: "Home life is anything but conventional. You may move frequently, have an unusual living arrangement, or experience sudden domestic changes. Inner awakenings and breakthroughs are common.",
    themes: ["Inner awakening", "Unconventional home", "Sudden changes", "Freedom"],
    bestFor: ["Personal breakthroughs", "Alternative living", "Breaking family patterns"],
    challenges: ["Domestic instability", "Restlessness", "Difficulty settling down"],
  },
  "uranus-ASC": {
    title: "Uranus on the Ascendant",
    shortDesc: "Your individuality line. You become uniquely yourself, eccentric, and brilliantly original.",
    livingHere: "You feel free to be completely yourself - quirks and all. Others see you as unique, original, and perhaps eccentric. Innovation comes naturally, and you attract unusual experiences.",
    themes: ["Individuality", "Freedom", "Originality", "Eccentricity"],
    bestFor: ["Self-discovery", "Creative innovation", "Technology", "Breaking free"],
    challenges: ["Alienation", "Unpredictability", "Difficulty with routine"],
  },
  "uranus-DSC": {
    title: "Uranus on the Descendant",
    shortDesc: "Your unconventional partnership line. Unusual, exciting, and unpredictable relationships.",
    livingHere: "Relationships here are exciting but unpredictable. You attract unconventional partners who challenge your expectations. Partnerships may start or end suddenly.",
    themes: ["Unconventional partnerships", "Excitement", "Freedom in relationships"],
    bestFor: ["Open-minded relationships", "Creative partnerships", "Meeting unusual people"],
    challenges: ["Relationship instability", "Commitment issues", "Sudden breakups"],
  },
  "neptune-MC": {
    title: "Neptune on the Midheaven",
    shortDesc: "Your dream line. Career in arts, spirituality, or healing. Reality becomes fluid here.",
    livingHere: "Your career becomes intertwined with creativity, spirituality, or healing. You may be drawn to music, film, photography, or spiritual work. Your public image has a dreamy, otherworldly quality.",
    themes: ["Creative career", "Spirituality", "Healing", "Imagination"],
    bestFor: ["Artistic career", "Spiritual work", "Healing professions", "Photography", "Music"],
    challenges: ["Career confusion", "Deception", "Lack of direction", "Addiction risk"],
  },
  "neptune-IC": {
    title: "Neptune at the Nadir",
    shortDesc: "Your spiritual home line. Deep connection to the divine, dreams, and inner mysticism.",
    livingHere: "This location dissolves boundaries between your inner world and the spiritual realm. Dreams become vivid, intuition sharpens, and you may feel a mystical connection to the land itself.",
    themes: ["Spiritual connection", "Dreams", "Mysticism", "Dissolution"],
    bestFor: ["Spiritual retreat", "Meditation practice", "Artistic inspiration", "Healing"],
    challenges: ["Escapism", "Confusion about identity", "Boundary issues", "Addiction risk"],
  },
  "neptune-ASC": {
    title: "Neptune on the Ascendant",
    shortDesc: "Your mystic line. You become ethereal, intuitive, and spiritually sensitive here.",
    livingHere: "You take on an ethereal, mysterious quality. Others see you as spiritual, compassionate, and otherworldly. Artistic and psychic abilities are heightened, but boundaries can blur.",
    themes: ["Mysticism", "Compassion", "Artistic sensitivity", "Psychic ability"],
    bestFor: ["Spiritual development", "Art and music", "Healing others", "Compassionate work"],
    challenges: ["Identity confusion", "Victimization", "Substance sensitivity", "Escapism"],
  },
  "neptune-DSC": {
    title: "Neptune on the Descendant",
    shortDesc: "Your soulmate dream line. Relationships have a karmic, spiritual, or idealized quality.",
    livingHere: "Relationships feel fated, spiritual, and deeply romantic. You attract sensitive, artistic partners. There's a danger of idealizing partners, but also the potential for truly transcendent love.",
    themes: ["Soulmate connections", "Spiritual love", "Idealization", "Karmic bonds"],
    bestFor: ["Finding spiritual partners", "Artistic collaboration", "Compassionate relationships"],
    challenges: ["Deception in relationships", "Idealizing partners", "Codependency", "Confusion"],
  },
  "pluto-MC": {
    title: "Pluto on the Midheaven",
    shortDesc: "Your power line. Intense transformation through career, influence, and authority.",
    livingHere: "Power and transformation define your public life. You may be drawn to psychology, investigation, research, or positions of hidden power. Your career undergoes profound transformations.",
    themes: ["Power", "Transformation", "Influence", "Intensity"],
    bestFor: ["Psychology", "Research", "Investigative work", "Power positions", "Transformation"],
    challenges: ["Power struggles", "Obsession with control", "Enemies", "Intense scrutiny"],
  },
  "pluto-IC": {
    title: "Pluto at the Nadir",
    shortDesc: "Your deep transformation line. Profound inner changes and psychological rebirth.",
    livingHere: "This is one of the most transformative lines. Deep psychological changes occur, often involving family secrets, ancestral patterns, or personal demons. What emerges is a completely transformed self.",
    themes: ["Deep transformation", "Psychology", "Family secrets", "Rebirth"],
    bestFor: ["Deep therapy", "Shadow work", "Ancestral healing", "Personal rebirth"],
    challenges: ["Intense emotions", "Family power struggles", "Obsessive behavior", "Crisis"],
  },
  "pluto-ASC": {
    title: "Pluto on the Ascendant",
    shortDesc: "Your transformation line. Complete personal metamorphosis and magnetic power.",
    livingHere: "You become intensely magnetic and powerful. Others feel your presence strongly. Personal transformation is inevitable - you shed old identities and emerge reborn. This line changes you forever.",
    themes: ["Personal transformation", "Magnetic power", "Intensity", "Rebirth"],
    bestFor: ["Personal reinvention", "Overcoming trauma", "Gaining personal power"],
    challenges: ["Intensity", "Paranoia", "Power struggles", "Obsessive behavior"],
  },
  "pluto-DSC": {
    title: "Pluto on the Descendant",
    shortDesc: "Your transformative partnership line. Relationships that change you at the deepest level.",
    livingHere: "Relationships here are transformative and intense. You attract powerful partners who change you fundamentally. These connections can be deeply healing or destructive - rarely anything in between.",
    themes: ["Transformative relationships", "Power dynamics", "Deep bonds", "Intensity"],
    bestFor: ["Transformative partnerships", "Deep healing through others", "Psychology"],
    challenges: ["Obsessive relationships", "Power struggles", "Jealousy", "Manipulation"],
  },
};

export function getInterpretation(planet: PlanetName, lineType: LineType): Interpretation {
  const key = `${planet}-${lineType}`;
  return (
    interpretations[key] || {
      title: `${planet} ${lineType}`,
      shortDesc: "Interpretation not available.",
      livingHere: "",
      themes: [],
      bestFor: [],
      challenges: [],
    }
  );
}

export function getPlanetSymbol(planet: PlanetName): string {
  const symbols: Record<PlanetName, string> = {
    sun: "Sun",
    moon: "Moon",
    mercury: "Mercury",
    venus: "Venus",
    mars: "Mars",
    jupiter: "Jupiter",
    saturn: "Saturn",
    uranus: "Uranus",
    neptune: "Neptune",
    pluto: "Pluto",
  };
  return symbols[planet] || planet;
}

export function getPlanetIcon(planet: PlanetName): string {
  const icons: Record<PlanetName, string> = {
    sun: "sunny",
    moon: "moon",
    mercury: "flash",
    venus: "heart",
    mars: "flame",
    jupiter: "star",
    saturn: "time",
    uranus: "thunderstorm",
    neptune: "water",
    pluto: "skull",
  };
  return icons[planet] || "planet";
}
